simple_access.settings:
  type: config_oject
  label: 'Global simple access settings'
  display:
    type: mapping
    label: 'Display access fields'
    mapping:
      view:
        type: boolean
        label: 'View'
      update:
        type: boolean
        label: 'Update'
      delete:
        type: boolean
        label: 'Delete'
  show_groups:
    type: boolean
    label: 'Show groups'

simple_access.group.*:
  type: config_entity
  label: 'Simple access group'
  mapping:
    id:
      type: string
      label: 'Id'
    label:
      type: label
      label: 'Label'
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
    weight:
      type: integer
      label: 'Weight'

simple_access.profile.*:
  type: config_entity
  label: 'Simple access profile'
  mapping:
    id:
      type: string
      label: 'Id'
    label:
      type: label
      label: 'Label'
    access:
      type: sequence
      label: 'Access'
      sequence:
        type: mapping
        mapping:
          group:
            type: string
            label: 'Group id'
          view:
            type: boolean
            label: 'View'
          update:
            type: boolean
            label: 'Update'
          delete:
            type: boolean
            label: 'Delete'
    weight:
      type: integer
      label: 'Weight'

node.type.*.third_party.simple_access:
  type: config_object
  label: 'Node default configuration'
  mapping:
    profiles:
      type: mapping
      label: 'Selected profiles'
      mapping:
        profiles:
          type: sequence
          label: 'Profiles to apply'
          sequence:
            type: string
        groups:
          type: mapping
          label: 'groups to apply'
          mapping:
            view:
              type: boolean
              label: 'View'
            update:
              type: boolean
              label: 'Update'
            delete:
              type: boolean
              label: 'Delete'
