# Schema for the views plugins of the Views XML Backend module.

views_xml_backend.xpath_selector:
  type: string
  label: 'XPath selector'

views.field.views_xml_backend_standard:
  type: views.field.prerender_list
  label: 'Views XML Backend text field'
  mapping:
    xpath_selector:
      type: views_xml_backend.xpath_selector

views.field.views_xml_backend_markup:
  type: views.field.views_xml_backend_standard
  label: 'Views XML Backend markup field'
  mapping:
    format:
      type: string
      label: 'Format'

views.field.views_xml_backend_date:
  type: views.field.views_xml_backend_standard
  label: 'Views XML Backend date field'
  mapping:
    date_format:
      type: string
      label: 'Date format'
    custom_date_format:
      type: string
      label: 'Custom date format'
    timezone:
      type: string
      label: 'Timezone'

views.filter.views_xml_backend_standard:
  type: views.filter.string
  label: 'Views XML Backend text filter'
  mapping:
    xpath_selector:
      type: views_xml_backend.xpath_selector

views.filter.views_xml_backend_numeric:
  type: views.filter.string
  label: 'Views XML Backend numeric filter'
  mapping:
    xpath_selector:
      type: views_xml_backend.xpath_selector
    value:
      type: views.filter_value.numeric

views.filter.views_xml_backend_date:
  type: views.filter.string
  label: 'Views XML Backend date filter'
  mapping:
    xpath_selector:
      type: views_xml_backend.xpath_selector
    value:
      type: views.filter_value.numeric

views.argument.views_xml_backend_standard:
  type: views_argument
  label: 'Views XML Backend text argument'
  mapping:
    xpath_selector:
      type: views_xml_backend.xpath_selector

views.argument.views_xml_backend_date:
  type: views.argument.date
  label: 'Views XML Backend text numeric'
  mapping:
    xpath_selector:
      type: views_xml_backend.xpath_selector

views.argument.views_xml_backend_numeric:
  type: views.argument.views_xml_backend_standard
  label: 'Views XML Backend text numeric'

views.argument.views_xml_backend_passthrough:
  type: views_argument
  label: 'Views XML Backend passthrough argument'

views.sort.views_xml_backend_standard:
  type: views_sort
  label: 'Views XML Backend standard sort'
  mapping:
    xpath_selector:
      type: views_xml_backend.xpath_selector

views.sort.views_xml_backend_numeric:
  type: views.sort.views_xml_backend_standard
  label: 'Views XML Backend numeric sort'

views.sort.views_xml_backend_date:
  type: views.sort.views_xml_backend_standard
  label: 'Views XML Backend date sort'

views.query.views_xml_backend:
  type: views_query
  label: 'Views XML Backend query'
  mapping:
    xml_file:
      type: string
      label: 'XML file'
    row_xpath:
      type: string
      label: 'Row XPath'
    default_namespace:
      type: string
      label: 'Default namespace'
    show_errors:
      type: boolean
      label: 'Show errors'
