# Schema for the configuration files of the mass_password_change module.

action.configuration.mass_password_reset_action:
  type: action_configuration_default
  label: 'Password reset the selected user(s)'
action.configuration.mass_password_change_action:
  type: action_configuration_default
  label: 'Change password the selected user(s)'
